[project]
name = "ecourts"
version = "0.0.1"
dependencies = [
    "PyYAML~=6.0",
    "requests~=2.31",
    "beautifulsoup4~=4.10",
    "pytest~=8.3",
    "opencv-python~=4.10.0",
    "wat-inspector",
    "html5lib",
    "pytest-recording~=0.13"
]
requires-python = ">=3.10"
description = ""
dynamic = ["version"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
testpaths = [
  "test"
]
[tool.hatch]
