name: Run Tests

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install .[docs,test]
        sudo apt install tesseract-ocr
    - name: Run tests
      run: pytest
